#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-D3
Version  : 3.1.6.2
Release  : 10
URL      : https://pypi.python.org/packages/source/X/XStatic-D3/XStatic-D3-3.1.6.2.tar.gz
Source0  : https://pypi.python.org/packages/source/X/XStatic-D3/XStatic-D3-3.1.6.2.tar.gz
Summary  : D3 3.1.6 (XStatic packaging standard)
Group    : Development/Tools
License  : BSD-3-Clause
Requires: XStatic-D3-python
BuildRequires : python-dev
BuildRequires : setuptools

%description
XStatic-D3
--------------
D3 JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-D3 package.
Group: Default

%description python
python components for the XStatic-D3 package.


%prep
%setup -q -n XStatic-D3-3.1.6.2

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
