#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : XStatic-D3
Version  : 3.5.17.0
Release  : 16
URL      : https://github.com/openstack/xstatic-d3/archive/3.5.17.0.tar.gz
Source0  : https://github.com/openstack/xstatic-d3/archive/3.5.17.0.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause
Requires: XStatic-D3-python3
Requires: XStatic-D3-python
BuildRequires : buildreq-distutils3
BuildRequires : pluggy
BuildRequires : py-python
BuildRequires : pytest
BuildRequires : tox
BuildRequires : virtualenv

%description
XStatic-D3
--------------
D3 JavaScript library packaged for setuptools (easy_install) / pip.

%package python
Summary: python components for the XStatic-D3 package.
Group: Default
Requires: XStatic-D3-python3
Provides: xstatic-d3-python

%description python
python components for the XStatic-D3 package.


%package python3
Summary: python3 components for the XStatic-D3 package.
Group: Default
Requires: python3-core

%description python3
python3 components for the XStatic-D3 package.


%prep
%setup -q -n xstatic-d3-3.5.17.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1533916015
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
